version: '3.8'
services:
  api-telemetry:
    image: telemetry-mio
    container_name: telemetry-mvz
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/telemetry_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      mysql-db:
        condition: service_healthy
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=telemetry_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql-container"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data: